### ISSUE TITLE
Cannot open/find downloaded files

### ISSUE THREAD

**Issue by jurf** [flathub/org.gnome.Epiphany#1]
When I download a file, everything is alright from UI, but clicking the file does nothing and nor does clicking the folder icon.

I tried doing a system-wide search for the file (including hidden files) but with no result. Downloading two files adds a “(1)” at the end.

**Comment by mcatanzaro** [comment]
This is https://bugzilla.gnome.org/show_bug.cgi?id=787850, let's track it there.

I just switched today to using flatpak for my daily browsing, and this is *really* annoying me, so I'll try to get to it soon. But help welcome of course.
