### ISSUE TITLE
Password manager not working

### ISSUE THREAD

**Issue by Retrotux** [flathub/org.gnome.Epiphany#10]
Referencing #3, I can also report that the password manager is currently not working in elementaryOS 5.1.4. (Hera). Epiphany Version is 3.36.1 (Flathub) and xdg-desktop-portal 1.6 is installed. Epiphany offers to store passwords, but there is no data shown in the settings menu.

**Comment by mcatanzaro** [comment]
OK, GitHub doesn't have duplicates I guess, but let's continue there in #3.

**Comment by TingPing** [comment]
The syntax is: `Duplicate of #3`

**Comment by mcatanzaro** [comment]
Good to be different.

Duplicate of #3

**Comment by mcatanzaro** [comment]
Duplicate of #3

**Comment by mcatanzaro** [comment]
It also has to be the only comment in the issue, apparently. OK....

**Comment by TingPing** [comment]
I wouldn't be surprised if Github had that before Gitlab, dunno.
