### ISSUE TITLE
Cannot store bookmarks

### ISSUE THREAD

**Issue by dschier-wtd** [flathub/org.gnome.Epiphany#16]
So far so good, but storing bookmarks seems not to work. Neither the star icon nor the shortcut are working.

I am running the following.

```
OS: Fedora 32 Silverblue
Flatpak: flatpak-1.8.2-2.fc32.x86_64
App: 

GNOME Web - Web browser for GNOME

          ID: org.gnome.Epiphany
         Ref: app/org.gnome.Epiphany/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.38.0
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 10,0 MB
     Runtime: org.gnome.Platform/x86_64/3.38
         Sdk: org.gnome.Sdk/x86_64/3.38

      Commit: b3be53f0efa4860921dd0d545084cf51b363a33fc8d653a5fc5d9d2318bc0e2f
      Parent: 890af214d5f6c3d7e2a3d1d5a3adc13d6ebce57c2459fee06b34e88f805f07a1
     Subject: bump to 3.38 (#14) (46dfcc2a)
        Date: 2020-09-17 22:13:55 +0000
```

Please feel free to give me a ping, If I can support you.

**Comment by mcatanzaro** [comment]
Are you still seeing this problem?

Any error messages in your terminal if you run `flatpak run --command=/bin/bash org.gnome.Epiphany` and then `epiphany` and then try to click the star icon?

**Comment by mcatanzaro** [comment]
My guess is database corruption not handled gracefully. There should hopefully be a warning message. Otherwise, this will be hard.

**Comment by dschier-wtd** [comment]
Hi @mcatanzaro, I just tested it with 41.3 and everything seems fine: No errors in the console. Thanks a lot for having a look.

**Comment by prog-amateur2** [comment]
> Hi @mcatanzaro, I just tested it with 41.3 and everything seems fine: No errors in the console. Thanks a lot for having a look.

Hello, the way you solve this issue is unclear for me : I have Gnome Web flatpak version 41.3 as you and I also have the same issue (no star). 
Are you sure only upgrading solved this issue or did you have downloaded something else / changed resolution or anything else ? Thank you for your kind feedback.

**Comment by dschier-wtd** [comment]
Hmmm, interesting. After the comment I just re-downloaded the flatpak and tested bookmarking. Nothing else. :/

**Comment by mcatanzaro** [comment]
> Hello, the way you solve this issue is unclear for me : I have Gnome Web flatpak version 41.3 as you and I also have the same issue (no star).

No warnings if you run Epiphany from the terminal? (`flatpak run org.gnome.Epiphany`)

**Comment by prog-amateur2** [comment]
Thank you both for your kind help. 
I confirm that opening Gnome Web with `flatpak run org.gnome.Epiphany` does not show any warning during opening or browsing. 
However I noticed that this missing star appear only in incognito-mode. Please find below to screenshots with same website in incognito-mode (no star) and normal session (star icon is shown). What do you think ? Thank you : 

![Capture d’écran de 2022-01-30 16-37-19](https://user-images.githubusercontent.com/60101083/151706549-40f0d400-786e-49ab-ba46-6049d2fdc7a2.png)
![Capture d’écran de 2022-01-30 16-37-58](https://user-images.githubusercontent.com/60101083/151706551-c58070b1-93ca-4d5d-acf7-14b81de8974a.png)

**Comment by mcatanzaro** [comment]
The bookmarks database is opened read-only in incognito mode, so you can't write bookmarks and the star is not shown.

I don't think this really makes sense to do, since bookmarks are not web-exposed, but it's certainly not a flathub-related issue.

**Comment by prog-amateur2** [comment]
Thank you for your explanation. I also think it should be better to be able to bookmark even in incognito mode. 
I would like to link this issue to the classic gnome web gitlab, hoping they will accept my request, but this is a real PAIN to sign in their gitlab. I can connect to many gitlab but not Gnome's one. I shall try later maybe it is a server issue or I don't know.
