### ISSUE TITLE
Web apps do not show up in the Shell

### ISSUE THREAD

**Issue by jurf** [flathub/org.gnome.Epiphany#2]
Title says it all really.

**Comment by TingPing** [comment]
Needs write access to `~/.local/share/applications` (which ofc kills any chance of sandboxing and needs to be a feature exposed by flatpak).

**Comment by mcatanzaro** [comment]
Creating web apps from within Epiphany is fundamentally incompatible with flatpak. This feature is supposed to be "disabled" by https://git.gnome.org/browse/epiphany/commit/?h=gnome-3-26&id=77a09886ee78af0bc1adad9c1d8b43b8691f2901 which removed the hamburger menu item to add a new web app and also the about:applications page. Can I ask where you've found this functionality still exposed?

Web apps can still be created by software developers and used in Flatpak, but it each one is going to need to be built separately and separately bundle Epiphany (unless we move Epiphany into the runtime, which might make sense).

**Comment by mcatanzaro** [comment]
Also please confirm that the version you see in the about dialog is 3.26.2.

**Comment by jurf** [comment]
It’s available under the right-click context menu. Yeah, I’ve wondered why it was so hard to find.

**Comment by mcatanzaro** [comment]
I'm confused, because I don't see it in the context menu... can you post step-by-step instructions for how to display this menu item? It looks like it's properly-hidden for me.

**Comment by jurf** [comment]
Now I’m confused too, it isn’t there anymore, but I definitely created it, it’s present under `~/.var/app/org.gnome.Epiphany/config/epiphany`. And yes, 3.26.2.

**Comment by mcatanzaro** [comment]
OK... since we don't know how you managed to do it, I'm going to go ahead and close this for now. But if you ever figure it out, please do leave another comment here and we can reopen.
