### ISSUE TITLE
Add site to desktop broken

### ISSUE THREAD

**Issue by JorisPLA7** [flathub/org.gnome.Epiphany#25]
`Ctrl + Shift + A` should open a prompt to add an icon of the opened web page to the desktop. It doesnt.

When I press these keys, nothing happens.

I have checked it's only occuring from the flatpack release. Works fine if Epiphany is installed by RPM.

I don't know if it's possible to do such a trick from inside a flatpak contained app, but I have hope it is! :pray: 
I'm on fedora  (`Linux fedora 5.13.7-200.fc34.x86_64`)

**Comment by mcatanzaro** [comment]
Not possible. Flatpak apps cannot install other apps. Sorry.
