### ISSUE TITLE
Doesn't stop running in the background

### ISSUE THREAD

**Issue by SuborbitalPigeon** [flathub/org.gnome.Epiphany#28]
Every time Epiphany is started, a new `epiphany` process is created. These don't stop when the program is closed, so I end up with many `epiphany` processes running at once.

**Comment by mcatanzaro** [comment]
What's especially impressive about this bug report is that it is a GApplication service. If another Epiphany process is running, a new process will just active the existing one and then quit immediately....

**Comment by SuborbitalPigeon** [comment]
Just noticed that all the `WebKitWebProcess`s also stay around, which is quite the memory sink.

**Comment by mcatanzaro** [comment]
This is one of the weirdest bug reports I've seen. How *exactly* are you launching Epiphany? Is it possible you're using an uncommon desktop environment that's failing to reap child processes? Are you sure the Epiphany process is really still running?

If you're certain the old processes are running, then something must be causing Epiphany to hang. You'll need to get a backtrace of the epiphany process that is hanging while it is running to see what it is doing. To do that, you'll want to run:

```
$ flatpak install org.gnome.Epiphany.Debug
$ flatpak install org.gnome.Platform.Debug
$ flatpak update
```

to install debuginfo and ensure consistent version. Then make sure to start the primary instance of Epiphany -- the one that is not hanging -- however you normally do so. Then start the second instance under gdb:

```
$ flatpak run -d --command=/bin/bash org.gnome.Epiphany
[📦 org.gnome.Epiphany ~]$ gdb epiphany
```

This will be very slow as gdb will take forever to start epiphany, but if you're patient it should eventually activate the primary instance and then quit. Except in your case, we want it to hit this strange hang instead. Hit Ctrl+C to get a backtrace and let's see what it says.

**Comment by mcatanzaro** [comment]
> Hit Ctrl+C to get a backtrace and let's see what it says.

And then run `bt` to see what it's doing. More detailed instructions [here](https://blogs.gnome.org/mcatanzaro/2021/09/18/creating-quality-backtraces-for-crash-reports/).

**Comment by SuborbitalPigeon** [comment]
It doesn't seem to happen any more. The only thing I've noticed lately is that there seem to be more `bwrap` processes than I'd expect based on the number of `WebKitWebProcess`es.

I've been using GNOME, so nothing odd should have been happening. Apologies for the ambiguous bug report, but I wasn't really sure what was going on at all.

**Comment by mcatanzaro** [comment]
Hm, well OK then!

> It doesn't seem to happen any more. The only thing I've noticed lately is that there seem to be more bwrap processes than I'd expect based on the number of WebKitWebProcesses.

It should be two bwrap processes per web process.
