### ISSUE TITLE
New screnshots

### ISSUE THREAD

**Issue by Byrdg** [flathub/org.gnome.Epiphany#29]
Hey, I have these screenshots (attached) that I think are better than the current one because they are more updated and align more on how the app looks now. If its OK to update them, can you please point me to the appdata XML source or update them?
![Screenshot from 2021-11-10 11-49-30](https://user-images.githubusercontent.com/94136706/141366864-69d9ce59-c877-43e4-a13e-08fab122e121.png)
![Screenshot from 2021-11-10 11-49-42](https://user-images.githubusercontent.com/94136706/141366872-72417f7b-182a-4c84-bef0-00e0524dc197.png)
![Screenshot from 2021-11-10 11-49-52](https://user-images.githubusercontent.com/94136706/141366876-a42584a7-6fdc-487f-92df-af48d20f8d17.png)
"

**Comment by mcatanzaro** [comment]
Hi, the source is here: https://gitlab.gnome.org/GNOME/epiphany/-/blob/master/data/org.gnome.Epiphany.appdata.xml.in.in

The existing screenshot is indeed looking pretty dated. Note the goal is to keep it vendor-neutral though, so you'd want to avoid advertising Endless or any other downstream distro. Let's either stick to GNOME and WebKit pages, or else find something silly and obviously neutral like cats or similar.

**Comment by Byrdg** [comment]
Thanks..
![Screenshot from 2021-11-11 16-01-09](https://user-images.githubusercontent.com/94136706/141369324-03e0131b-f2a9-4fd5-9e9d-a4a1a50d846e.png)
![Screenshot from 2021-11-11 16-01-48](https://user-images.githubusercontent.com/94136706/141369329-013b69fe-9d58-439f-87f3-a312a68dd4d0.png)
![Screenshot from 2021-11-11 16-08-26](https://user-images.githubusercontent.com/94136706/141369342-15397462-72d6-43c2-be64-28009d33bfeb.png)
.

**Comment by mcatanzaro** [comment]
Hi, please make sure to use default settings when taking your screenshots. There shouldn't be minimize or maximize buttons, and for some reason your close button looks different, which is odd because the rest of the buttons look like normal GNOME icons. Are you using a custom icon theme?

**Comment by mcatanzaro** [comment]
Yeah, the weird close buttons are more obvious if you look at your browser tabs. I think you've got a custom icon theme, and the rest of the icons are just weirdly similar to GNOME's?

I think you've configured a special font, too? The text on the tabs does not look like Cantarel. That's probably not noticeable enough to matter -- I wouldn't have noticed except I was squinting at your tabs due to the oversized close buttons -- so we can ignore it I suppose, but ideally screenshots should be taken with everything set to defaults.

**Comment by Exalm** [comment]
Kinda. These are defaults in Endless.

These screenshots also should be smaller and should have shadows.

**Comment by Exalm** [comment]
See the Screenshots section in https://blogs.gnome.org/tbernard/2021/09/07/ready-for-software-41/

**Comment by mcatanzaro** [comment]
> Edit: also please no non-overlay scrollbars

I missed that!

I'm going to suggest using a live image of some distro that doesn't mess with GNOME defaults. Fedora, openSUSE, Debian, or GNOME OS would all be good as these distros don't mess with themes or fonts or scrollbars.

**Comment by mcatanzaro** [comment]
Closing since these screenshots aren't usable. Needs to be fixed in GNOME anyway, not in the flathub packaging.
