### ISSUE TITLE
Private mode does keep history

### ISSUE THREAD

**Issue by prog-amateur2** [flathub/org.gnome.Epiphany#31]
Hello, I am on Web 41.3 Flatpak version. 
In private mode, it is said : 
`You are currently browsing in private mode. The pages consulted in this way do not appear in your browsing history and any information in memory will be destroyed when you close the window.`

However, if I go on History menu I have all my browsing experience even after closing the window. 
Could you please check and feedback if this issue is confirmed on your side ? Thank you very much

**Comment by TingPing** [comment]
Briefly testing I cannot reproduce.

**Comment by mcatanzaro** [comment]
You're sure that you're seeing history from other incognito sessions, and not the normal history pulled in from your non-incognito session?

**Comment by prog-amateur2** [comment]
Thank you both for checking ! 
@mcatanzaro was right : history stored was before incognito session, I did not noticed it and I was surprised to see URLs in my history (I thought that once you setup Privacy mode, you can see history from normal and privacy session). 

Therefore, let's close this issue, however if you want you can reopen it. 

Thank you again for having helped me !
