### ISSUE TITLE
Flatpak doesn't work in dark mode

### ISSUE THREAD

**Issue by aomgiwjc** [flathub/org.gnome.Epiphany#34]
Attempting to switch to "Dark Mode" in the latest Flatpak leaves it in light mode. Do not experience this problem with native version. Installed 1.10.7 on Debian Bullseye.

**Comment by mcatanzaro** [comment]
Closing since Epiphany is a GTK 3 app still. Dark mode is a libadwaita feature. It's not available until we've switched to GTK 4.
