### ISSUE TITLE
Web 44 fails to launch from desktop entry

### ISSUE THREAD

**Issue by philipstewart** [flathub/org.gnome.Epiphany#49]
Hi,

After updating to version 44, I can no longer launch Web from the desktop entry in the application overview.

I observe the following:
```
$ coredumpctl dump
           PID: 2523 (epiphany)
           UID: 1000 (<snip>)
           GID: 1000 (<snip>)
        Signal: 11 (SEGV)
     Timestamp: Sat 2023-03-25 15:31:51 GMT (2min 52s ago)
  Command Line: epiphany
    Executable: /app/bin/epiphany
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-flatpak-org.gnome.Epiphany-2498.scope
          Unit: user@1000.service
     User Unit: app-flatpak-org.gnome.Epiphany-2498.scope
         Slice: user-1000.slice
     Owner UID: 1000 (<snip>)
       Boot ID: 33bcbd020e7943c98569e1157a002a59
    Machine ID: <snip>
      Hostname: <snip>
       Storage: /var/lib/systemd/coredump/core.epiphany.1000.33bcbd020e7943c98569e1157a002a59.2523.1679758311000000.zst
       Message: Process 2523 (epiphany) of user 1000 dumped core.
                
                Stack trace of thread 2:
                #0  0x00007f76ee63220c n/a (/usr/lib/x86_64-linux-gnu/libwayland-client.so.0.21.0 + 0x920c)
                #1  0x00007f76f5c0b197 n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1000.1 + 0x47e197)
                #2  0x00007f76f6327efe n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7600.0 + 0x1defe)
                #3  0x00007f76f632b2d9 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7600.0 + 0x212d9)
                #4  0x00007f76f632be8f n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7600.0 + 0x21e8f)
                #5  0x00007f76f5a45498 n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1000.1 + 0x2b8498)
                #6  0x00007f76f632265a n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7600.0 + 0x1865a)
                #7  0x00007f76f633d66f n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7600.0 + 0x3366f)
                #8  0x00007f76f633d873 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7600.0 + 0x33873)
                #9  0x00007f76f5a324d8 n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1000.1 + 0x2a54d8)
                #10 0x00007f76f5a4502a n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1000.1 + 0x2b802a)
                #11 0x00007f76f64599f1 n/a (/app/lib/epiphany/libephymain.so + 0x899f1)
                #12 0x00007f76f632265a n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7600.0 + 0x1865a)
                #13 0x00007f76f633d66f n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7600.0 + 0x3366f)
                #14 0x00007f76f633d873 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7600.0 + 0x33873)
                #15 0x00007f76f5a27fd4 n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1000.1 + 0x29afd4)
                #16 0x00007f76f644fc0e n/a (/app/lib/epiphany/libephymain.so + 0x7fc0e)
                #17 0x00007f76f644ffa0 n/a (/app/lib/epiphany/libephymain.so + 0x7ffa0)
                #18 0x00007f76f6458fe4 n/a (/app/lib/epiphany/libephymain.so + 0x88fe4)
                #19 0x00007f76eed54056 n/a (/usr/lib/x86_64-linux-gnu/libffi.so.8.1.2 + 0x9056)
                #20 0x00007ffd6f488720 n/a (n/a + 0x0)
```

Launching from a terminal using `flatpak run org.gnome.Epiphany` works fine.

I see the same behaviour on both my machines and I confirmed on the second that I could still launch Web via the icon on the second machine before upgrading to 44.

I have tried another application (`org.gnome.TextEditor`) using the 44 runtime to confirm that it can launch from the desktop entry successfully.

I have tried completely removing and reinstalling Web.

I'm using Debian 11.6 with Flatpak 1.10.7.

I'm not sure what to try next and would welcome advice!

Cheers,
Phil

**Comment by mcatanzaro** [comment]
Hi, you'll need to install debuginfo (`org.gnome.Sdk.Debug//44` and `org.gnome.Epiphany.Debug`) and then take the backtrace with gdb (`flatpak-coredumpctl org.gnome.Epiphany` then `bt full`).

**Comment by philipstewart** [comment]
Thanks, included the warnings before `bt full` in case relevant: [2023-03-25-epiphany-bt.txt](https://github.com/flathub/org.gnome.Epiphany/files/11069964/2023-03-25-epiphany-bt.txt)

**Comment by mcatanzaro** [comment]
Good backtrace.

> I'm using Debian 11.6 with Flatpak 1.10.7.

What desktop environment and version?

This looks like a GTK bug that occurs when the compositor does not support xdg_activation_v1. GTK should simply not attempt to do startup notification in this case. In particular, gdk_wayland_toplevel_set_startup_id() needs to null-check `display->xdg_activation` before using it. Next step for you is to take that backtrace, report it [here](https://gitlab.gnome.org/GNOME/gtk/-/issues), and then post a link here so that I can follow. Thanks!

**Comment by philipstewart** [comment]
Thanks @mcatanzaro, I'm on GNOME 3.38

I will report it at the GTK GitLab and post back, just waiting for my account to be approved.

Have a great weekend!
