### ISSUE TITLE
does not load video from twitch

### ISSUE THREAD

**Issue by dinhokusanagi** [flathub/org.gnome.Epiphany#6]
stays on infinite loading

![test](https://user-images.githubusercontent.com/43162113/81484758-9a159000-921e-11ea-8b82-3cfbfd026615.png)

**Comment by mcatanzaro** [comment]
https://gitlab.com/freedesktop-sdk/openh264-extension/-/issues/9

**Comment by Marukesu** [comment]
i don't known if it's valid here, but I'm using the tech preview and i still can't reproduce twitch. have org.freedesktop.openh264 installed from both  flathub and gnome-nightly repo.
