### ISSUE TITLE
Can't log in with my Firefox Sync account

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gnome.Epiphany#8]
![Captura de tela de 2020-05-09 20-31-04](https://user-images.githubusercontent.com/26097419/81487526-5037a480-9234-11ea-924d-a4d924908318.png)
```
** (epiphany:3): WARNING **: 20:35:11.221: Failed to store sync secrets: org.freedesktop.DBus.Error.ServiceUnknown

```

**Comment by mcatanzaro** [comment]
Upgrade to xdg-desktop-portal 1.6.

See https://github.com/flatpak/xdg-desktop-portal/issues/483 for why we prefer to break secret storage rather than expose host libsecret.

**Comment by mcatanzaro** [comment]
To clarify: we prefer to break secret storage on old host systems rather than store the secrets and then let you discover that they have all disappeared once you upgrade your host system in the future. This way, if it fails to store secrets initially, at least you don't suffer data loss.

**Comment by tim77** [comment]
@mcatanzaro i have the same issue and `xdg-desktop-portal-1.7.2-1` on Fedora 32. Should we reopen this issue or should tracking https://github.com/flatpak/xdg-desktop-portal/issues/483?

**Comment by mcatanzaro** [comment]
> i have the same issue and `xdg-desktop-portal-1.7.2-1` on Fedora 32. Should we reopen this issue or should tracking [flatpak/xdg-desktop-portal#483](https://github.com/flatpak/xdg-desktop-portal/issues/483)?

OK, that's unfortunate. You must have a different issue that hasn't been reported yet. Definitely please report a new issue. Go ahead and use the upstream bugtracker at https://gitlab.gnome.org/GNOME/epiphany/-/issues/.

**Comment by tim77** [comment]
:arrow_right: https://gitlab.gnome.org/GNOME/epiphany/-/issues/1233
